// C header generated by hand to match the FFI surface in
// ../../../core/src/ffi.rs. Bump in lockstep with any signature
// change there.

#ifndef CSM_CORE_H
#define CSM_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

// Every csm_* call returns a UTF-8 JSON string that the caller must
// free with csm_string_free. Ownership rule keeps the FFI thin: add
// a JSON field on the Rust side and neither host has to recompile.
char *csm_list_sessions(void);
char *csm_load_session_detail(const char *session_id);
char *csm_metadata_load(void);
int   csm_metadata_save(const char *json);
void  csm_string_free(char *ptr);

#ifdef __cplusplus
}
#endif

#endif
